export const constants={
    USERS_FETCH:'USERS_FETCH',
    SET_EDIT:'SET_EDIT',
    GET_CREDS:'GET_CREDS',
    GET_PROFILE:'GET_PROFILE',
    GET_USER:'GET_USER',
    GET_CRED:'GET_CRED',
    GET_REGISTRATIONS:'GET_REGISTRATIONS'
}